version: '3'

services:

  web:
    container_name: web
    image: ${DOCKER_REPO}/oven-web
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Seoul

  flask:
    container_name: flask
    image: see101702/flask-image
    expose:
      - "5000"
    depends_on:
      - web
    environment:
      - TZ=Asia/Seoul

  nginx:
    container_name: nginx
    image: ${DOCKER_REPO}/oven-nginx
    ports:
      - "80:80"
    depends_on:
      - web
    environment:
      - TZ=Asia/Seoul

  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"
    environment:
      - TZ=Asia/Seoul